name: ServerPause
version: 2.5
main: org.example.Main
api-version: 26.1.2 # Adjust this to match your target Minecraft version

commands:
  serverpausereload:
    description: Nothing.
    usage: /serverpausereload
  joinserver:
    description: Nothing.
    usage: /joinserver
